name: rauandesantana
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
  # JoKenPo
    - assets/projetos/jokenpo/fullscreen_historico_lista.png
    - assets/projetos/jokenpo/fullscreen_historico_vazio.png
    - assets/projetos/jokenpo/fullscreen_modo_adivinhe.png
    - assets/projetos/jokenpo/fullscreen_modo_combate.png
    - assets/projetos/jokenpo/fullscreen_pagina_nao_encontrada.png
    - assets/projetos/jokenpo/fullscreen_resetar_dialogo.png
    - assets/projetos/jokenpo/historico_lista.png
    - assets/projetos/jokenpo/historico_vazio.png
    - assets/projetos/jokenpo/modo_adivinhe_derrota.png
    - assets/projetos/jokenpo/modo_adivinhe_inicial.png
    - assets/projetos/jokenpo/modo_adivinhe_vitoria.png
    - assets/projetos/jokenpo/modo_combate_derrota.png
    - assets/projetos/jokenpo/modo_combate_empate.png
    - assets/projetos/jokenpo/modo_combate_inicial.png
    - assets/projetos/jokenpo/modo_combate_vitoria.png
    - assets/projetos/jokenpo/pagina_nao_encontrada.png
    - assets/projetos/jokenpo/resetar_dialogo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700